FROM python:3.12-slim@sha256:f77ac9e44ae96ef2c90b8053ea08c31f8be030f824196b0ae4db6d462c84e51f
RUN pip install --no-cache-dir wsgidav==4.3.5 cheroot==11.1.2
COPY wsgidav.py /opt/waybill-test/server.py
CMD ["python", "/opt/waybill-test/server.py"]
